// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmrServiceClient is the client API for EmrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmrServiceClient interface {
	Search(ctx context.Context, in *EmrSearchRequest, opts ...grpc.CallOption) (*EmrSearchResponse, error)
	Service(ctx context.Context, in *EmrRequest, opts ...grpc.CallOption) (*EmrServiceListResponse, error)
	OPDScreening(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDScreenResponse, error)
	OPDDiagnosis(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDDiagResponse, error)
	OPDProcedure(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDProcedureResponse, error)
	OPDDrug(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDDrugResponse, error)
	OPDLab(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDLabResponse, error)
	Appointment(ctx context.Context, in *EmrSearchRequest, opts ...grpc.CallOption) (*EmrAppointmentResponse, error)
	ReferOut(ctx context.Context, in *EmrSearchRequest, opts ...grpc.CallOption) (*EmrReferOutResponse, error)
}

type emrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmrServiceClient(cc grpc.ClientConnInterface) EmrServiceClient {
	return &emrServiceClient{cc}
}

func (c *emrServiceClient) Search(ctx context.Context, in *EmrSearchRequest, opts ...grpc.CallOption) (*EmrSearchResponse, error) {
	out := new(EmrSearchResponse)
	err := c.cc.Invoke(ctx, "/proto.EmrService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emrServiceClient) Service(ctx context.Context, in *EmrRequest, opts ...grpc.CallOption) (*EmrServiceListResponse, error) {
	out := new(EmrServiceListResponse)
	err := c.cc.Invoke(ctx, "/proto.EmrService/Service", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emrServiceClient) OPDScreening(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDScreenResponse, error) {
	out := new(EmrOPDScreenResponse)
	err := c.cc.Invoke(ctx, "/proto.EmrService/OPDScreening", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emrServiceClient) OPDDiagnosis(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDDiagResponse, error) {
	out := new(EmrOPDDiagResponse)
	err := c.cc.Invoke(ctx, "/proto.EmrService/OPDDiagnosis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emrServiceClient) OPDProcedure(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDProcedureResponse, error) {
	out := new(EmrOPDProcedureResponse)
	err := c.cc.Invoke(ctx, "/proto.EmrService/OPDProcedure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emrServiceClient) OPDDrug(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDDrugResponse, error) {
	out := new(EmrOPDDrugResponse)
	err := c.cc.Invoke(ctx, "/proto.EmrService/OPDDrug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emrServiceClient) OPDLab(ctx context.Context, in *EmrServiceRequest, opts ...grpc.CallOption) (*EmrOPDLabResponse, error) {
	out := new(EmrOPDLabResponse)
	err := c.cc.Invoke(ctx, "/proto.EmrService/OPDLab", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emrServiceClient) Appointment(ctx context.Context, in *EmrSearchRequest, opts ...grpc.CallOption) (*EmrAppointmentResponse, error) {
	out := new(EmrAppointmentResponse)
	err := c.cc.Invoke(ctx, "/proto.EmrService/Appointment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emrServiceClient) ReferOut(ctx context.Context, in *EmrSearchRequest, opts ...grpc.CallOption) (*EmrReferOutResponse, error) {
	out := new(EmrReferOutResponse)
	err := c.cc.Invoke(ctx, "/proto.EmrService/ReferOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmrServiceServer is the server API for EmrService service.
// All implementations must embed UnimplementedEmrServiceServer
// for forward compatibility
type EmrServiceServer interface {
	Search(context.Context, *EmrSearchRequest) (*EmrSearchResponse, error)
	Service(context.Context, *EmrRequest) (*EmrServiceListResponse, error)
	OPDScreening(context.Context, *EmrServiceRequest) (*EmrOPDScreenResponse, error)
	OPDDiagnosis(context.Context, *EmrServiceRequest) (*EmrOPDDiagResponse, error)
	OPDProcedure(context.Context, *EmrServiceRequest) (*EmrOPDProcedureResponse, error)
	OPDDrug(context.Context, *EmrServiceRequest) (*EmrOPDDrugResponse, error)
	OPDLab(context.Context, *EmrServiceRequest) (*EmrOPDLabResponse, error)
	Appointment(context.Context, *EmrSearchRequest) (*EmrAppointmentResponse, error)
	ReferOut(context.Context, *EmrSearchRequest) (*EmrReferOutResponse, error)
	mustEmbedUnimplementedEmrServiceServer()
}

// UnimplementedEmrServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmrServiceServer struct {
}

func (UnimplementedEmrServiceServer) Search(context.Context, *EmrSearchRequest) (*EmrSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedEmrServiceServer) Service(context.Context, *EmrRequest) (*EmrServiceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Service not implemented")
}
func (UnimplementedEmrServiceServer) OPDScreening(context.Context, *EmrServiceRequest) (*EmrOPDScreenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OPDScreening not implemented")
}
func (UnimplementedEmrServiceServer) OPDDiagnosis(context.Context, *EmrServiceRequest) (*EmrOPDDiagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OPDDiagnosis not implemented")
}
func (UnimplementedEmrServiceServer) OPDProcedure(context.Context, *EmrServiceRequest) (*EmrOPDProcedureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OPDProcedure not implemented")
}
func (UnimplementedEmrServiceServer) OPDDrug(context.Context, *EmrServiceRequest) (*EmrOPDDrugResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OPDDrug not implemented")
}
func (UnimplementedEmrServiceServer) OPDLab(context.Context, *EmrServiceRequest) (*EmrOPDLabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OPDLab not implemented")
}
func (UnimplementedEmrServiceServer) Appointment(context.Context, *EmrSearchRequest) (*EmrAppointmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Appointment not implemented")
}
func (UnimplementedEmrServiceServer) ReferOut(context.Context, *EmrSearchRequest) (*EmrReferOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReferOut not implemented")
}
func (UnimplementedEmrServiceServer) mustEmbedUnimplementedEmrServiceServer() {}

// UnsafeEmrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmrServiceServer will
// result in compilation errors.
type UnsafeEmrServiceServer interface {
	mustEmbedUnimplementedEmrServiceServer()
}

func RegisterEmrServiceServer(s grpc.ServiceRegistrar, srv EmrServiceServer) {
	s.RegisterService(&EmrService_ServiceDesc, srv)
}

func _EmrService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmrSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmrServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmrService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmrServiceServer).Search(ctx, req.(*EmrSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmrService_Service_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmrServiceServer).Service(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmrService/Service",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmrServiceServer).Service(ctx, req.(*EmrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmrService_OPDScreening_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmrServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmrServiceServer).OPDScreening(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmrService/OPDScreening",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmrServiceServer).OPDScreening(ctx, req.(*EmrServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmrService_OPDDiagnosis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmrServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmrServiceServer).OPDDiagnosis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmrService/OPDDiagnosis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmrServiceServer).OPDDiagnosis(ctx, req.(*EmrServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmrService_OPDProcedure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmrServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmrServiceServer).OPDProcedure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmrService/OPDProcedure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmrServiceServer).OPDProcedure(ctx, req.(*EmrServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmrService_OPDDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmrServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmrServiceServer).OPDDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmrService/OPDDrug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmrServiceServer).OPDDrug(ctx, req.(*EmrServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmrService_OPDLab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmrServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmrServiceServer).OPDLab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmrService/OPDLab",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmrServiceServer).OPDLab(ctx, req.(*EmrServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmrService_Appointment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmrSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmrServiceServer).Appointment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmrService/Appointment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmrServiceServer).Appointment(ctx, req.(*EmrSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmrService_ReferOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmrSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmrServiceServer).ReferOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmrService/ReferOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmrServiceServer).ReferOut(ctx, req.(*EmrSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmrService_ServiceDesc is the grpc.ServiceDesc for EmrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EmrService",
	HandlerType: (*EmrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _EmrService_Search_Handler,
		},
		{
			MethodName: "Service",
			Handler:    _EmrService_Service_Handler,
		},
		{
			MethodName: "OPDScreening",
			Handler:    _EmrService_OPDScreening_Handler,
		},
		{
			MethodName: "OPDDiagnosis",
			Handler:    _EmrService_OPDDiagnosis_Handler,
		},
		{
			MethodName: "OPDProcedure",
			Handler:    _EmrService_OPDProcedure_Handler,
		},
		{
			MethodName: "OPDDrug",
			Handler:    _EmrService_OPDDrug_Handler,
		},
		{
			MethodName: "OPDLab",
			Handler:    _EmrService_OPDLab_Handler,
		},
		{
			MethodName: "Appointment",
			Handler:    _EmrService_Appointment_Handler,
		},
		{
			MethodName: "ReferOut",
			Handler:    _EmrService_ReferOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/emr.proto",
}
