// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.8
// source: refer.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// refer list
type ReferListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hospcode string `protobuf:"bytes,1,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
	Hn       string `protobuf:"bytes,2,opt,name=hn,proto3" json:"hn,omitempty"`
	Date     string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *ReferListRequest) Reset() {
	*x = ReferListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReferListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferListRequest) ProtoMessage() {}

func (x *ReferListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferListRequest.ProtoReflect.Descriptor instead.
func (*ReferListRequest) Descriptor() ([]byte, []int) {
	return file_refer_proto_rawDescGZIP(), []int{0}
}

func (x *ReferListRequest) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

func (x *ReferListRequest) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *ReferListRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ReferListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ReferListResponse_Results `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ReferListResponse) Reset() {
	*x = ReferListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReferListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferListResponse) ProtoMessage() {}

func (x *ReferListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferListResponse.ProtoReflect.Descriptor instead.
func (*ReferListResponse) Descriptor() ([]byte, []int) {
	return file_refer_proto_rawDescGZIP(), []int{1}
}

func (x *ReferListResponse) GetResults() []*ReferListResponse_Results {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReferListResponse_Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hospcode     string `protobuf:"bytes,1,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
	Hospname     string `protobuf:"bytes,2,opt,name=hospname,proto3" json:"hospname,omitempty"`
	TitleName    string `protobuf:"bytes,3,opt,name=title_name,json=titleName,proto3" json:"title_name,omitempty"`
	FirstName    string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName     string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Birthdate    string `protobuf:"bytes,6,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Sex          string `protobuf:"bytes,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Cid          string `protobuf:"bytes,8,opt,name=cid,proto3" json:"cid,omitempty"`
	Hn           string `protobuf:"bytes,9,opt,name=hn,proto3" json:"hn,omitempty"`
	ContactTel   string `protobuf:"bytes,10,opt,name=contact_tel,json=contactTel,proto3" json:"contact_tel,omitempty"`
	ContactName  string `protobuf:"bytes,11,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ProviderName string `protobuf:"bytes,12,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	HisProvider  string `protobuf:"bytes,13,opt,name=his_provider,json=hisProvider,proto3" json:"his_provider,omitempty"`
	Txid         string `protobuf:"bytes,14,opt,name=txid,proto3" json:"txid,omitempty"`
}

func (x *ReferListResponse_Results) Reset() {
	*x = ReferListResponse_Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReferListResponse_Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferListResponse_Results) ProtoMessage() {}

func (x *ReferListResponse_Results) ProtoReflect() protoreflect.Message {
	mi := &file_refer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferListResponse_Results.ProtoReflect.Descriptor instead.
func (*ReferListResponse_Results) Descriptor() ([]byte, []int) {
	return file_refer_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ReferListResponse_Results) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

func (x *ReferListResponse_Results) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

func (x *ReferListResponse_Results) GetTitleName() string {
	if x != nil {
		return x.TitleName
	}
	return ""
}

func (x *ReferListResponse_Results) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ReferListResponse_Results) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ReferListResponse_Results) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *ReferListResponse_Results) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *ReferListResponse_Results) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ReferListResponse_Results) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *ReferListResponse_Results) GetContactTel() string {
	if x != nil {
		return x.ContactTel
	}
	return ""
}

func (x *ReferListResponse_Results) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *ReferListResponse_Results) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ReferListResponse_Results) GetHisProvider() string {
	if x != nil {
		return x.HisProvider
	}
	return ""
}

func (x *ReferListResponse_Results) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

var File_refer_proto protoreflect.FileDescriptor

var file_refer_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x10, 0x52, 0x65, 0x66, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x68, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0xe0, 0x03, 0x0a, 0x11, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a,
	0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x8e, 0x03, 0x0a, 0x07, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69,
	0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x68,
	0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x74, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x54, 0x65, 0x6c, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x69, 0x73, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x32, 0x50, 0x0a, 0x0c, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_refer_proto_rawDescOnce sync.Once
	file_refer_proto_rawDescData = file_refer_proto_rawDesc
)

func file_refer_proto_rawDescGZIP() []byte {
	file_refer_proto_rawDescOnce.Do(func() {
		file_refer_proto_rawDescData = protoimpl.X.CompressGZIP(file_refer_proto_rawDescData)
	})
	return file_refer_proto_rawDescData
}

var file_refer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_refer_proto_goTypes = []interface{}{
	(*ReferListRequest)(nil),          // 0: proto.ReferListRequest
	(*ReferListResponse)(nil),         // 1: proto.ReferListResponse
	(*ReferListResponse_Results)(nil), // 2: proto.ReferListResponse.Results
}
var file_refer_proto_depIdxs = []int32{
	2, // 0: proto.ReferListResponse.results:type_name -> proto.ReferListResponse.Results
	0, // 1: proto.ReferService.ReferList:input_type -> proto.ReferListRequest
	1, // 2: proto.ReferService.ReferList:output_type -> proto.ReferListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_refer_proto_init() }
func file_refer_proto_init() {
	if File_refer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_refer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReferListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReferListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReferListResponse_Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_refer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_refer_proto_goTypes,
		DependencyIndexes: file_refer_proto_depIdxs,
		MessageInfos:      file_refer_proto_msgTypes,
	}.Build()
	File_refer_proto = out.File
	file_refer_proto_rawDesc = nil
	file_refer_proto_goTypes = nil
	file_refer_proto_depIdxs = nil
}
