// Copyright 2021 ICT@MOPH.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: src/ems.proto

package grpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EmsPatientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *EmsPatientRequest) Reset() {
	*x = EmsPatientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsPatientRequest) ProtoMessage() {}

func (x *EmsPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsPatientRequest.ProtoReflect.Descriptor instead.
func (*EmsPatientRequest) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{0}
}

func (x *EmsPatientRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type EmsPatientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*EmsPatientResponse_Results `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *EmsPatientResponse) Reset() {
	*x = EmsPatientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsPatientResponse) ProtoMessage() {}

func (x *EmsPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsPatientResponse.ProtoReflect.Descriptor instead.
func (*EmsPatientResponse) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{1}
}

func (x *EmsPatientResponse) GetResults() []*EmsPatientResponse_Results {
	if x != nil {
		return x.Results
	}
	return nil
}

type EmsPatientResponse_Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hospcode   string `protobuf:"bytes,1,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
	Hn         string `protobuf:"bytes,2,opt,name=hn,proto3" json:"hn,omitempty"`
	Cid        string `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Passport   string `protobuf:"bytes,4,opt,name=passport,proto3" json:"passport,omitempty"`
	TitleName  string `protobuf:"bytes,5,opt,name=title_name,json=titleName,proto3" json:"title_name,omitempty"`
	FirstName  string `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName   string `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	GenderId   string `protobuf:"bytes,8,opt,name=gender_id,json=genderId,proto3" json:"gender_id,omitempty"`
	Birthdate  string `protobuf:"bytes,9,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	GwRecordId string `protobuf:"bytes,10,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
}

func (x *EmsPatientResponse_Results) Reset() {
	*x = EmsPatientResponse_Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsPatientResponse_Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsPatientResponse_Results) ProtoMessage() {}

func (x *EmsPatientResponse_Results) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsPatientResponse_Results.ProtoReflect.Descriptor instead.
func (*EmsPatientResponse_Results) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EmsPatientResponse_Results) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetTitleName() string {
	if x != nil {
		return x.TitleName
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetGenderId() string {
	if x != nil {
		return x.GenderId
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

var File_src_ems_proto protoreflect.FileDescriptor

var file_src_ems_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x72, 0x63, 0x2f, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x25, 0x0a, 0x11, 0x45, 0x6d, 0x73, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0xee, 0x02, 0x0a,
	0x12, 0x45, 0x6d, 0x73, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x73, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a,
	0x9b, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x67,
	0x77, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x67, 0x77, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x32, 0x50, 0x0a,
	0x0a, 0x45, 0x6d, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x45, 0x6d, 0x73, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x73, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x65, 0x6d, 0x73, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_ems_proto_rawDescOnce sync.Once
	file_src_ems_proto_rawDescData = file_src_ems_proto_rawDesc
)

func file_src_ems_proto_rawDescGZIP() []byte {
	file_src_ems_proto_rawDescOnce.Do(func() {
		file_src_ems_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_ems_proto_rawDescData)
	})
	return file_src_ems_proto_rawDescData
}

var file_src_ems_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_ems_proto_goTypes = []interface{}{
	(*EmsPatientRequest)(nil),          // 0: grpc.EmsPatientRequest
	(*EmsPatientResponse)(nil),         // 1: grpc.EmsPatientResponse
	(*EmsPatientResponse_Results)(nil), // 2: grpc.EmsPatientResponse.Results
}
var file_src_ems_proto_depIdxs = []int32{
	2, // 0: grpc.EmsPatientResponse.results:type_name -> grpc.EmsPatientResponse.Results
	0, // 1: grpc.EmsService.PatientInfo:input_type -> grpc.EmsPatientRequest
	1, // 2: grpc.EmsService.PatientInfo:output_type -> grpc.EmsPatientResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_ems_proto_init() }
func file_src_ems_proto_init() {
	if File_src_ems_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_ems_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsPatientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ems_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsPatientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ems_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsPatientResponse_Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_ems_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_ems_proto_goTypes,
		DependencyIndexes: file_src_ems_proto_depIdxs,
		MessageInfos:      file_src_ems_proto_msgTypes,
	}.Build()
	File_src_ems_proto = out.File
	file_src_ems_proto_rawDesc = nil
	file_src_ems_proto_goTypes = nil
	file_src_ems_proto_depIdxs = nil
}
