// Copyright 2021 ICT@MOPH.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: src/ems.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmsPatientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *EmsPatientRequest) Reset() {
	*x = EmsPatientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsPatientRequest) ProtoMessage() {}

func (x *EmsPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsPatientRequest.ProtoReflect.Descriptor instead.
func (*EmsPatientRequest) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{0}
}

func (x *EmsPatientRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type EmsPatientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*EmsPatientResponse_Results `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *EmsPatientResponse) Reset() {
	*x = EmsPatientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsPatientResponse) ProtoMessage() {}

func (x *EmsPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsPatientResponse.ProtoReflect.Descriptor instead.
func (*EmsPatientResponse) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{1}
}

func (x *EmsPatientResponse) GetResults() []*EmsPatientResponse_Results {
	if x != nil {
		return x.Results
	}
	return nil
}

type EmsVisitCountMaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*EmsVisitCountMaxResponse_Results `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *EmsVisitCountMaxResponse) Reset() {
	*x = EmsVisitCountMaxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsVisitCountMaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsVisitCountMaxResponse) ProtoMessage() {}

func (x *EmsVisitCountMaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsVisitCountMaxResponse.ProtoReflect.Descriptor instead.
func (*EmsVisitCountMaxResponse) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{2}
}

func (x *EmsVisitCountMaxResponse) GetResults() []*EmsVisitCountMaxResponse_Results {
	if x != nil {
		return x.Results
	}
	return nil
}

type EmsHospitalLatestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*EmsHospitalLatestResponse_Results `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *EmsHospitalLatestResponse) Reset() {
	*x = EmsHospitalLatestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsHospitalLatestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsHospitalLatestResponse) ProtoMessage() {}

func (x *EmsHospitalLatestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsHospitalLatestResponse.ProtoReflect.Descriptor instead.
func (*EmsHospitalLatestResponse) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{3}
}

func (x *EmsHospitalLatestResponse) GetResults() []*EmsHospitalLatestResponse_Results {
	if x != nil {
		return x.Results
	}
	return nil
}

type EmsPatientResponse_Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid      string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Hospcode string `protobuf:"bytes,2,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
	Hospname string `protobuf:"bytes,3,opt,name=hospname,proto3" json:"hospname,omitempty"`
	Hn       string `protobuf:"bytes,4,opt,name=hn,proto3" json:"hn,omitempty"`
	Count    string `protobuf:"bytes,5,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *EmsPatientResponse_Results) Reset() {
	*x = EmsPatientResponse_Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsPatientResponse_Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsPatientResponse_Results) ProtoMessage() {}

func (x *EmsPatientResponse_Results) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsPatientResponse_Results.ProtoReflect.Descriptor instead.
func (*EmsPatientResponse_Results) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EmsPatientResponse_Results) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *EmsPatientResponse_Results) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

type EmsVisitCountMaxResponse_Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid      string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Hospcode string `protobuf:"bytes,2,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
	Hospname string `protobuf:"bytes,3,opt,name=hospname,proto3" json:"hospname,omitempty"`
	Hn       string `protobuf:"bytes,4,opt,name=hn,proto3" json:"hn,omitempty"`
}

func (x *EmsVisitCountMaxResponse_Results) Reset() {
	*x = EmsVisitCountMaxResponse_Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsVisitCountMaxResponse_Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsVisitCountMaxResponse_Results) ProtoMessage() {}

func (x *EmsVisitCountMaxResponse_Results) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsVisitCountMaxResponse_Results.ProtoReflect.Descriptor instead.
func (*EmsVisitCountMaxResponse_Results) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{2, 0}
}

func (x *EmsVisitCountMaxResponse_Results) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *EmsVisitCountMaxResponse_Results) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

func (x *EmsVisitCountMaxResponse_Results) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

func (x *EmsVisitCountMaxResponse_Results) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

type EmsHospitalLatestResponse_Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid      string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Hospcode string `protobuf:"bytes,2,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
	Hospname string `protobuf:"bytes,3,opt,name=hospname,proto3" json:"hospname,omitempty"`
	Hn       string `protobuf:"bytes,4,opt,name=hn,proto3" json:"hn,omitempty"`
	An       string `protobuf:"bytes,5,opt,name=an,proto3" json:"an,omitempty"`
	Vstdate  string `protobuf:"bytes,6,opt,name=vstdate,proto3" json:"vstdate,omitempty"`
	Vsttime  string `protobuf:"bytes,7,opt,name=vsttime,proto3" json:"vsttime,omitempty"`
}

func (x *EmsHospitalLatestResponse_Results) Reset() {
	*x = EmsHospitalLatestResponse_Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ems_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsHospitalLatestResponse_Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsHospitalLatestResponse_Results) ProtoMessage() {}

func (x *EmsHospitalLatestResponse_Results) ProtoReflect() protoreflect.Message {
	mi := &file_src_ems_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsHospitalLatestResponse_Results.ProtoReflect.Descriptor instead.
func (*EmsHospitalLatestResponse_Results) Descriptor() ([]byte, []int) {
	return file_src_ems_proto_rawDescGZIP(), []int{3, 0}
}

func (x *EmsHospitalLatestResponse_Results) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *EmsHospitalLatestResponse_Results) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

func (x *EmsHospitalLatestResponse_Results) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

func (x *EmsHospitalLatestResponse_Results) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *EmsHospitalLatestResponse_Results) GetAn() string {
	if x != nil {
		return x.An
	}
	return ""
}

func (x *EmsHospitalLatestResponse_Results) GetVstdate() string {
	if x != nil {
		return x.Vstdate
	}
	return ""
}

func (x *EmsHospitalLatestResponse_Results) GetVsttime() string {
	if x != nil {
		return x.Vsttime
	}
	return ""
}

var File_src_ems_proto protoreflect.FileDescriptor

var file_src_ems_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x72, 0x63, 0x2f, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x25, 0x0a, 0x11, 0x45, 0x6d, 0x73, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0xcb, 0x01, 0x0a,
	0x12, 0x45, 0x6d, 0x73, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x73, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a,
	0x79, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x68, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc1, 0x01, 0x0a, 0x18, 0x45,
	0x6d, 0x73, 0x56, 0x69, 0x73, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x61, 0x78, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x45, 0x6d, 0x73, 0x56, 0x69, 0x73, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x61, 0x78,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x63, 0x0a, 0x07, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x68, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x6e, 0x22, 0x88,
	0x02, 0x0a, 0x19, 0x45, 0x6d, 0x73, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x4c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x73, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c,
	0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a,
	0xa7, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73,
	0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73,
	0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73, 0x74, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x32, 0xea, 0x01, 0x0a, 0x0a, 0x45, 0x6d,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45,
	0x6d, 0x73, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x73, 0x50, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0e,
	0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x73, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45,
	0x6d, 0x73, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x56, 0x69,
	0x73, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x61, 0x78, 0x12, 0x17, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x6d, 0x73, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x73, 0x56,
	0x69, 0x73, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x65, 0x6d, 0x73, 0x3b,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_ems_proto_rawDescOnce sync.Once
	file_src_ems_proto_rawDescData = file_src_ems_proto_rawDesc
)

func file_src_ems_proto_rawDescGZIP() []byte {
	file_src_ems_proto_rawDescOnce.Do(func() {
		file_src_ems_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_ems_proto_rawDescData)
	})
	return file_src_ems_proto_rawDescData
}

var file_src_ems_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_src_ems_proto_goTypes = []interface{}{
	(*EmsPatientRequest)(nil),                 // 0: grpc.EmsPatientRequest
	(*EmsPatientResponse)(nil),                // 1: grpc.EmsPatientResponse
	(*EmsVisitCountMaxResponse)(nil),          // 2: grpc.EmsVisitCountMaxResponse
	(*EmsHospitalLatestResponse)(nil),         // 3: grpc.EmsHospitalLatestResponse
	(*EmsPatientResponse_Results)(nil),        // 4: grpc.EmsPatientResponse.Results
	(*EmsVisitCountMaxResponse_Results)(nil),  // 5: grpc.EmsVisitCountMaxResponse.Results
	(*EmsHospitalLatestResponse_Results)(nil), // 6: grpc.EmsHospitalLatestResponse.Results
}
var file_src_ems_proto_depIdxs = []int32{
	4, // 0: grpc.EmsPatientResponse.results:type_name -> grpc.EmsPatientResponse.Results
	5, // 1: grpc.EmsVisitCountMaxResponse.results:type_name -> grpc.EmsVisitCountMaxResponse.Results
	6, // 2: grpc.EmsHospitalLatestResponse.results:type_name -> grpc.EmsHospitalLatestResponse.Results
	0, // 3: grpc.EmsService.PatientInfo:input_type -> grpc.EmsPatientRequest
	0, // 4: grpc.EmsService.HospitalLatest:input_type -> grpc.EmsPatientRequest
	0, // 5: grpc.EmsService.VisitCountMax:input_type -> grpc.EmsPatientRequest
	1, // 6: grpc.EmsService.PatientInfo:output_type -> grpc.EmsPatientResponse
	3, // 7: grpc.EmsService.HospitalLatest:output_type -> grpc.EmsHospitalLatestResponse
	2, // 8: grpc.EmsService.VisitCountMax:output_type -> grpc.EmsVisitCountMaxResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_src_ems_proto_init() }
func file_src_ems_proto_init() {
	if File_src_ems_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_ems_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsPatientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ems_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsPatientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ems_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsVisitCountMaxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ems_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsHospitalLatestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ems_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsPatientResponse_Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ems_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsVisitCountMaxResponse_Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ems_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsHospitalLatestResponse_Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_ems_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_ems_proto_goTypes,
		DependencyIndexes: file_src_ems_proto_depIdxs,
		MessageInfos:      file_src_ems_proto_msgTypes,
	}.Build()
	File_src_ems_proto = out.File
	file_src_ems_proto_rawDesc = nil
	file_src_ems_proto_goTypes = nil
	file_src_ems_proto_depIdxs = nil
}
